### ISSUE TITLE
Errores detectados: Abel (19/04/18)

### ISSUE THREAD

**Issue by AbelChT** [SpreadYourMusic/Backend#36]
Los siguientes fallos son basados en: https://github.com/SpreadYourMusic/Backend/blob/develop/API.md
Nº1: POST /users/{nick}/login
Si hay una sesión abierta y se vuelve a autentificar el usuario, se cierra la sesión anterior.
Esto impediría el uso de la aplicación móvil y la web en paralelo.

Nº2: POST /users/{nick}/signup y resto de categorías que difieren:
Los campos necesarios para crear la cuenta son: nombre de usuario, nombre real, foto de usuario (url), biografía, email, password (una sola vez, la comprobación de si los dos passwords introducidos son iguales se realiza en el front-end), fecha de nacimiento, cuenta de twitter, cuenta de facebook y cuenta de instagram. (https://github.com/SpreadYourMusic/Documentation/blob/master/Arquitectura/Database.png)

Nº3: https://github.com/SpreadYourMusic/Documentation/blob/master/Arquitectura/Database.png
No existe soporte para los albumes. 
Un album ha de contar con nombre, fecha de lanzamiento, creador y url de su caratula.
Las canciones han de estar asociadas a álbumes obligatoriamente.

Nº4: https://github.com/SpreadYourMusic/Documentation/blob/master/Arquitectura/Database.png y GET /songs/{id}
Las canciones han de poseer la dirección el la que están almacenadas(url).

**Comment by lAngelP** [comment]
Nº1: Anotado para solucionarlo

Nº2: Anotado para solucionarlo, se añadirá a la petición de actualización de usuario al ser campos opcionales.

Nº3: Ya está @off94 con ello.

Nº4: La URL de la canción es automática y no se almacenará en la base de datos. Anotado para solucionarlo.

**Comment by off94** [comment]
Nº3 Listo

**Comment by lAngelP** [comment]
Nº 2 solucionado

**Comment by lAngelP** [comment]
Para el número 1 se ha cambiado para que regenere el token sólo si ha caducado, así Web y Android comparten el token

**Comment by lAngelP** [comment]
Además. en el número 1 se ha añadido un contador y si llega a cero se elimina el token.
