### ISSUE TITLE
Problema al borrar un usuario al que le estan siguiendo

### ISSUE THREAD

**Issue by jorpilo** [SpreadYourMusic/Backend#61]
El usuario A sigue a B
Actualmente si se borra el usuario A, el usuario B también se borra
Debería ser si se borra el usuario A, al B no le pasa nada

**Comment by lAngelP** [comment]
Esto es problema de un cascade mal puesto, ahora lo reviso

**Comment by lAngelP** [comment]
Revisalo de nuevo, ya debería estar solucionado
