### ISSUE TITLE
Error: Cuando seintenta obtener la información de un usuario que no existe da error 500

### ISSUE THREAD

**Issue by AbelChT** [SpreadYourMusic/Backend#69]

**Comment by lAngelP** [comment]
Qué peticion estás haciendo?
Yo hago un GET a http://155.210.13.105:7800/users/aefpiwef y me funciona correctamente.

**Comment by AbelChT** [comment]
Sigue dando error cuando el usuario existe 
Ejemplo: http://155.210.13.105:7800/users/abel/feed?nRepr=1
Si no salta la excepción

**Comment by AbelChT** [comment]
Este ya está corregido, antes daba java.lang.NullPointerException
